'''
cosine similarity heatmap after pca
The Tf-Idf generated by skrub.StringEncoder is the exception; 
it includes an internal SVD (PCA-like) step by default, 
so it is already low-dimensional.
'''

import re
import time

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import cosine_similarity

from strable.configs.path_configs import path_configs
from strable.plots.plot_setup import TODAYS_FOLDER
from strable.src.encoding import prepare_tabvec

# --- 2. CONFIG & PATHS ---
df_name = 'hospitals'
base_path = f'{path_configs["base_path"]}/data/llm_embeding'
# Adjust raw data path to where your original CSV/Parquet lives
processed_data_path = f'{path_configs["path_data_processed"]}/{df_name}/data.parquet' 
processed_json_path = f'{path_configs["path_data_processed"]}/{df_name}/config.json'

#read the json
import json
with open(processed_json_path, 'r') as f:
    processed_json = json.load(f)

print(f"Processing dataset: {df_name}...")

# Dictionary to store processed numpy arrays for the heatmap
embeddings_dict = {}

# --- 3. LOAD LLM EMBEDDINGS (Pre-computed) ---
llm_models = {
    'MiniLM-L6-v2': f'{base_path}/llm-all-MiniLM-L6-v2/llm-all-MiniLM-L6-v2|{df_name}.parquet',
    'LLaMA-3.1-8B': f'{base_path}/llm-llama-3.1-8b/llm-llama-3.1-8b|{df_name}.parquet',
    'Qwen3-8B': f'{base_path}/llm-qwen3-8b/llm-qwen3-8b|{df_name}.parquet'
}

for name, path in llm_models.items():
    try:
        df = pd.read_parquet(path)
        emb_cols = [c for c in df.columns if re.match(r'^X\d+$', c)]
        emb_cols.sort(key=lambda x: int(x[1:]))
        embeddings_dict[name] = df[emb_cols].values
        print(f"Loaded {name} shape: {embeddings_dict[name].shape}")
    except Exception as e:
        print(f"Could not load {name}: {e}")

# --- 4. GENERATE STRINGENCODER EMBEDDINGS (Live) ---
try:
    print("Generating StringEncoder (TabVec) embeddings...")
    # Loading the raw features (not the embeddings) to pass into your function
    X_raw = pd.read_parquet(processed_data_path) 

    #drop target column if exists
    X_raw = X_raw.drop(columns=[processed_json['target_name']], errors='ignore')

    # Use your function to get the feature matrix
    xt_encoded = prepare_tabvec(X_raw)
    
    # If it's a sparse matrix (skrub sometimes returns sparse), convert to dense
    if hasattr(xt_encoded, "toarray"):
        embeddings_dict['Tf-Idf'] = xt_encoded.toarray()
    else:
        embeddings_dict['Tf-Idf'] = xt_encoded.values if hasattr(xt_encoded, 'values') else xt_encoded
    
    print(f"Generated Tf-Idf shape: {embeddings_dict['Tf-Idf'].shape}")
except Exception as e:
    print(f"Failed to generate Tf-Idf: {e}")

# --- 5. PLOTTING HEATMAPS (With PCA applied) ---
plot_order = ['LLaMA-3.1-8B', 'Qwen3-8B', 'Tf-Idf', 'MiniLM-L6-v2']
fig, axes = plt.subplots(2, 2, figsize=(6, 6)) # Increased size slightly
axes_flat = axes.flatten()

for i, name in enumerate(plot_order):
    if name not in embeddings_dict:
        continue
        
    embs = embeddings_dict[name]
    ax = axes_flat[i]
    
    # --- STEP A: APPLY PCA (Simulation of prepare_llm) ---
    # We only apply PCA to LLMs. Tf-Idf (StringEncoder) is already dimension 30.
    if name != 'Tf-Idf':
        # We fit PCA on the available unique embeddings to simulate the reduction
        pca = PCA(n_components=30, random_state=1234)
        embs_reduced = pca.fit_transform(embs)
    else:
        # Tf-Idf is already reduced by skrub
        embs_reduced = embs

    # --- STEP B: SELECT SAMPLES FOR HEATMAP ---
    # Take first 50 samples from the REDUCED embeddings
    sample_size = min(50, embs_reduced.shape[0])
    embs_heat = embs_reduced[:sample_size]
    
    # Compute similarity
    sim_matrix = cosine_similarity(embs_heat)
    
    # Calculate Mean Similarity (ignoring diagonal)
    mask = ~np.eye(sim_matrix.shape[0], dtype=bool)
    avg_sim = sim_matrix[mask].mean()
    
    # Plotting
    sns.heatmap(
        sim_matrix, 
        ax=ax, 
        cmap='viridis', 
        vmin=0, 
        vmax=1, 
        square=True, 
        cbar=True,
        cbar_kws={"shrink": 0.8}
    )
    
    # Update title to reflect PCA status
    status = " (30-PCA)" if name != 'Tf-Idf' else "+ SVD (Internal)"
    ax.set_title(f"{name}{status}\nAvg CosSim: {avg_sim:.3f}", fontsize=11, fontweight='bold', pad=10)
    
    ax.set_xticks([])
    ax.set_yticks([])
    ax.axis('on')

plt.tight_layout()
today_date = time.strftime("%Y-%m-%d")
format = 'pdf'
PIC_NAME = f'avg_cosine_sim_matrix_after_30_pca_{df_name}_{today_date}.{format}'
plt.savefig(f'{path_configs["base_path"]}'+'/results_pics/'+ f"{TODAYS_FOLDER}/" + PIC_NAME, bbox_inches='tight')
plt.show()